import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:petpal/core/providers/firebase_providers.dart';
import 'package:petpal/core/theme/app_theme.dart';
import 'package:petpal/core/widgets/glass_card.dart';
import 'package:petpal/core/widgets/lottie_animation_overlay.dart';
import 'package:petpal/features/sitting/domain/entities/sitter_review.dart';
import 'package:petpal/features/sitting/presentation/providers/review_provider.dart';

class ReviewSubmissionSheet extends ConsumerStatefulWidget {
  final String sitterId;
  final String bookingId;
  final String sitterName;
  final bool isRepeatBooking;

  const ReviewSubmissionSheet({
    super.key,
    required this.sitterId,
    required this.bookingId,
    required this.sitterName,
    this.isRepeatBooking = false,
  });

  @override
  ConsumerState<ReviewSubmissionSheet> createState() =>
      _ReviewSubmissionSheetState();
}

class _ReviewSubmissionSheetState extends ConsumerState<ReviewSubmissionSheet> {
  double _rating = 0;
  final TextEditingController _commentController = TextEditingController();
  final List<String> _selectedTags = [];
  bool _showSuccess = false;

  final List<String> _sittingTags = [
    'שקט ונעים',
    'עדכונים שוטפים',
    'מקצועי',
    'אוהב חיות',
    'גמיש',
    'אחראי',
  ];

  void _toggleTag(String tag) {
    setState(() {
      if (_selectedTags.contains(tag)) {
        _selectedTags.remove(tag);
      } else {
        _selectedTags.add(tag);
      }
    });
    HapticFeedback.lightImpact();
  }

  Future<void> _submit() async {
    if (_rating == 0) return;

    final user = ref.read(authStateChangesProvider).asData?.value;
    final ownerId = user?.uid ?? 'anonymous';

    final review = SitterReview(
      id: '', // Will be generated by Firestore
      bookingId: widget.bookingId,
      sitterId: widget.sitterId,
      ownerId: ownerId,
      rating: _rating,
      comment: _commentController.text.isEmpty ? null : _commentController.text,
      vibeTags: _selectedTags,
      imageUrls: const [],
      createdAt: DateTime.now(),
    );

    await ref.read(reviewControllerProvider.notifier).submitReview(review);

    if (_rating >= 4.5) {
      setState(() => _showSuccess = true);
    } else {
      if (mounted) Navigator.pop(context);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Container(
          padding: EdgeInsets.only(
            bottom: MediaQuery.of(context).viewInsets.bottom,
          ),
          child: GlassCard(
            borderRadius: const BorderRadius.vertical(top: Radius.circular(32)),
            padding: const EdgeInsets.all(24),
            child: SingleChildScrollView(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  // Header
                  Center(
                    child: Container(
                      width: 40,
                      height: 4,
                      decoration: BoxDecoration(
                        color: AppColors.textMuted.withValues(alpha: 0.3),
                        borderRadius: BorderRadius.circular(2),
                      ),
                    ),
                  ),
                  const SizedBox(height: 24),
                  Text(
                    'איך היה השירות של ${widget.sitterName}?',
                    style: AppTextStyles.headlineMd,
                    textAlign: TextAlign.center,
                  ),
                  const SizedBox(height: 8),
                  Text(
                    widget.isRepeatBooking
                        ? 'דירוג מהיר עבור הזמנה חוזרת'
                        : 'שתף את החוויה שלך עם השכונה',
                    style: AppTextStyles.labelMd,
                    textAlign: TextAlign.center,
                  ),
                  const SizedBox(height: 32),

                  // Star Rating
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: List.generate(5, (index) {
                      final starValue = index + 1.0;
                      return IconButton(
                        onPressed: () {
                          setState(() => _rating = starValue);
                          HapticFeedback.mediumImpact();
                        },
                        icon: Icon(
                          _rating >= starValue
                              ? Icons.star_rounded
                              : Icons.star_outline_rounded,
                          size: 48,
                          color: _rating >= starValue
                              ? AppColors.warning
                              : AppColors.textMuted.withValues(alpha: 0.3),
                        ),
                      );
                    }),
                  ),
                  const SizedBox(height: 32),

                  // Vibe Tags
                  Text(
                    'מה בלט לטובה?',
                    style: AppTextStyles.bodyBold,
                  ),
                  const SizedBox(height: 12),
                  Wrap(
                    spacing: 8,
                    runSpacing: 8,
                    children: _sittingTags.map((tag) {
                      final isSelected = _selectedTags.contains(tag);
                      return FilterChip(
                        label: Text(tag),
                        selected: isSelected,
                        onSelected: (_) => _toggleTag(tag),
                        backgroundColor: AppColors.pureWhite,
                        selectedColor: AppColors.primary.withValues(alpha: 0.2),
                        checkmarkColor: AppColors.primary,
                        labelStyle: AppTextStyles.labelMd.copyWith(
                          color: isSelected
                              ? AppColors.primary
                              : AppColors.onSurface,
                          fontWeight:
                              isSelected ? FontWeight.w700 : FontWeight.w500,
                        ),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(12),
                          side: BorderSide(
                            color: isSelected
                                ? AppColors.primary
                                : AppColors.border,
                          ),
                        ),
                      );
                    }).toList(),
                  ),

                  if (!widget.isRepeatBooking) ...[
                    const SizedBox(height: 32),
                    // Comment field
                    Text(
                      'ספר לנו עוד (אופציונלי)',
                      style: AppTextStyles.bodyBold,
                    ),
                    const SizedBox(height: 12),
                    TextField(
                      controller: _commentController,
                      maxLines: 3,
                      decoration: InputDecoration(
                        hintText: 'האם Max היה שמח? איך הייתה התקשורת?',
                        hintStyle: AppTextStyles.labelMd,
                      ),
                    ),
                  ],

                  const SizedBox(height: 40),

                  // Submit Button
                  ElevatedButton(
                    onPressed: _rating > 0 ? _submit : null,
                    style: ElevatedButton.styleFrom(
                      padding: const EdgeInsets.symmetric(vertical: 18),
                      backgroundColor: AppColors.primary,
                      disabledBackgroundColor:
                          AppColors.textMuted.withValues(alpha: 0.2),
                    ),
                    child: const Text('שלח משוב וקבל +10 Karma'),
                  ),
                  const SizedBox(height: 16),
                ],
              ),
            ),
          ),
        ),

        // Success Overlay
        LottieAnimationOverlay(
          isVisible: _showSuccess,
          lottieAsset:
              'https://assets10.lottiefiles.com/packages/lf20_myejioos.json', // Dog wagging tail
          onComplete: () {
            Navigator.pop(context);
          },
        ),
      ],
    );
  }
}
